run_type = "sampling"
device = "cpu"
json_out_config = "_sampling.json"

[parameters]
model_file = "backend/uploads/prior_1_TL_reinvent/TL_reinvent.model"
output_file = "/home/omarf/Projects/Drug-Discovery/backend/logic/../../backend/results/sampling.csv"
num_smiles = 100
randomize_smiles = true
unique_molecules = true
