run_type = "sampling"
device = "cuda:0"
json_out_config = "_sampling.json"

[parameters]
model_file = "/home/omarf/Projects/Drug-Discovery/REINVENT4/priors/reinvent.prior"
output_file = "/home/omarf/Projects/Drug-Discovery/backend/logic/../../backend/results/sampling.csv"
num_smiles = 174
randomize_smiles = true
unique_molecules = true
